apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: kubeflow-user-example-com
  annotations:
     serving.kserve.io/s3-endpoint: s3.${CLUSTER_REGION}.amazonaws.com # replace with your s3 endpoint
     serving.kserve.io/s3-usehttps: "1" # by default 1, for testing with minio you need to set to 0
     serving.kserve.io/s3-region: "${CLUSTER_REGION}" # replace with the region the bucket is created in
     serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore credential provided and use anonymous credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ** # replace with your base64 encoded minio credential
  AWS_SECRET_ACCESS_KEY: ** # replace with your base64 encoded minio credential
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: kubeflow-user-example-com
secrets:
  - name: mysecret
---
apiVersion: v1
kind: Secret
metadata:
  name: mlpipeline-minio-artifact
  namespace: kubeflow-user-example-com
type: Opaque
data:
  accesskey: **
  secretkey: **
  region: dXMtd2VzdC0y
